title: Integrative Genomics
subtitle: by the Lücken Lab at the Computational Health Center
description: A GitHub based website for the Lücken Lab at CHC Helmholtz.
header: images/midjourney_lung.png
footer: images/midjourney_lung.png
links:
  email: malte.lucken@helmholtz-munich.de
  github: lueckenlab
  twitter: mdluecken
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@lueckenlab.com
github: lueckenlab
twitter: lueckenlab
instagram: lueckenlab
youtube: lueckenlab
